ping:
	gcc -o ping ping.c -lpthread

icmp_flood:
	gcc -o icmp_flood icmp_flood.c -lpthread

udp_flood:
	gcc -o udp_flood udp_flood.c -lpthread

syn_flood:
	gcc -o syn_flood syn_flood.c -lpthread

clean:
	$(RM) ping icmp_flood udp_flood syn_flood
